spring.application.name=HongPak_SpringBoot
# h2DB ??? ? ? ??
spring.h2.console.enabled=true
# sql? ??? ????? ?? ????
spring.jpa.defer-datasource-initialization=true
# jpa ????
# DEBUG LEVEL
logging.level.org.hibernate.SQL=DEBUG
# FORMAT
spring.jpa.properties.hibernate.format_sql=true
# SHOW Parameter
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# DB URL static setting
# No Unique URL
spring.datasource.generate-unique-name=false
# static URL
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL